### ISSUE TITLE
const keyword in strict mode breaks Safari 9.x

### ISSUE THREAD

**Issue by krzyzak00** [nfriedly/set-cookie-parser#20]
Since version 2.2.0 there's a const declaration that break older Safari browsers.
`const cookiesStrings = [];`
Safari throws `SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.` exception.

**Comment by nfriedly** [comment]
I never really expected for this to be used in browsers, but if you want to send a PR that changes that and anything else needed to run in Safari, I'll merge it in. 

(Does anybody still use Safari 9?)

**Comment by wojtekmaj** [comment]
Hi @nfriedly,
while I partially agree that people using Safari 9 may be "asking for it", please mind that many people rely on your work and expect semantic versioning rules to be followed.

As you did not define `engines` in package.lock, people may assume that whatever version of Node/browser set-cookie-parser works, it will continue to do so unless there is a breaking change in the package.

Adding a single `const` raises up minimum Node requirement to 6.0 and - as you can see - also raises minimum browser requirements. As such, version 2.2.0 may not be considered a non-breaking change. It should have been released as 3.0 if you would like to introduce new syntax. I suggest doing the following:

1. Changing `const` to `var`
2. Releasing `v2.2.1` which fixes the issue
3. Deprecating `v2.2.0` using `npm deprecate` so that the users won't be affected by this release

OR

1. Introducing a compiler, like Babel with `@babel/env`, which would allow you to use modern syntax while keeping the compatibility
pts 2-3 the same

Cheers!

**Comment by nfriedly** [comment]
I don't really disagree with you. This wasn't an *intentional* breaking change, I just merged in a different PR that added React Native support. 

I'm only on a phone right now, so it's a lot easier to merge in a PR than it is to edit and test the code. If you guys can send me a PR, I can merge it, and I have scripts set up to automatically do a git tag and npm publish based on the message in the merge commit.

Additionally, since browser support is obviously more important than I realized, I think some additional testing or at least linting is in order. If you tweak eslint to enforce es5 syntax, that should prevent this kind issue, and if you really want to go all-out, you could set up karma and saucelabs to actually run the tests in old browsers.

But, like I said, if you guys can send in a pull request with however much of that you want implemented, I can go ahead and merge it and get it released pretty quickly.

**Comment by nfriedly** [comment]
Now that I'm back at a computer, I set up eslint to enforce es5 mode on the library and replaced the `let`/`const` declarations with `var`. CI should publish `v2.2.1` within a few minutes
