### ISSUE TITLE
How could access Set-Cookie from header?

### ISSUE THREAD

**Issue by ceciliazcx** [nfriedly/set-cookie-parser#33]
This might not be a related question, but I tried very very long time but I cannot find a way to get Set-Cookie. Plus, there is an answer said Set-Cookie is forbidden to get from client
https://stackoverflow.com/questions/54214657/not-able-to-read-set-cookie-response-header

But I saw this library, is there any way I can get Set-Cookie header? Thanks.

**Comment by nfriedly** [comment]
Op, I saw your other comment first, but I'll copy-paste my [answer from there](https://github.com/nfriedly/set-cookie-parser/issues/13#issuecomment-600051648) to make it easy to find:

> @ceciliazcx The short version is that access to the set-cookie header is not allowed in the fetch spec, but Node.js and React Native go ahead and allow it anyways. If you're not in one of those two environments, though, you shouldn't expect to have access to the header. (To be clear, "regular" React running in a browser will not have access to the set-cookie header from a fetch request.)
>
> This library was intended for server side usage in Node.js, and then extended to work with React Native. You might be able to get it to work in other contexts, but it's not a guarantee.

If you're working in a web browser, then that stack overflow answer is basically correct. 

If you control the server, you could also add some `X-My-Custom-Header: cookies` and an `Access-Control-Allow-Headers: X-My-Custom-Header`header and then parse that instead of the `Set-Cookie` header. 

Alternatively, you can set up a second server that makes a request to the first one and grabs the Set-Cookie header. 

It's a security thing: JavaScript on one site shouldn't be able to access cookies from another site.
